name: Build and Publish Docker

on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  OWNER_NAME: deploygate
  IMAGE_NAME: deploygate-mock-server

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.OWNER_NAME }}
          password: ${{ github.token }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER_NAME }}/${{ env.IMAGE_NAME }}

      - uses: docker/build-push-action@v5.2.0
        with:
          context: .
          target: ghcr
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
